// Hopline — one dictionary per language. The toggle swaps the whole object, so
// no screen can ever mix the two. Korean body copy stays on Pretendard
// (--font-sans); the display face is reserved for digits, URLs and the wordmark.

import type { Lang, PeriodId } from "./data";

const EN = {
  brand: "Hopline",
  productLine: "Link analytics",
  workspace: "Fieldnote Studio",
  skipToWork: "Skip to what needs fixing",
  header: {
    search: "Search links, sources, tags",
    searchKey: "K",
    notifications: "Notifications, 3 unread",
    account: "Account menu for Mira Cho",
    accountInitials: "MC",
    language: "Language",
    langKo: "KO",
    langEn: "EN",
    langKoName: "Korean",
    langEnName: "English",
    period: "Reporting period",
    updated: "Updated",
  },
  periods: { "7d": "7 days", "28d": "28 days", "90d": "90 days" } as Record<
    PeriodId,
    string
  >,
  band: {
    h1: "What to fix today",
    lede: "Three things are costing you clicks right now. Everything below is ordered by what it asks you to do.",
    totalLabel: "Total clicks",
    vsPrev: "vs previous period",
    uniqueLabel: "Unique visitors",
    uniqueRead: "Repeat rate 28.4% — read totals as reach, not people.",
    brokenLabel: "Clicks into a 404",
    brokenRead: "One link accounts for all of it. See item 1.",
    activeLabel: "Active links",
    activeRead: "New this period, all pointing at the launch page.",
    chartTitle: "Clicks over time",
    chartHelp: "Bucketed to keep every period at a readable density.",
    markerPrefix: "Marked on the chart",
    clearMarker: "Clear marker",
    srCaption: "Clicks per bucket for the selected period",
    srDate: "Bucket",
    srValue: "Clicks",
    read: "Read",
  },
  todo: {
    h2: "Do this",
    lede: "Each card carries its own evidence and one prescription. Nothing here is a banner.",
    counter: (done: number, all: number) => `${done} of ${all} handled`,
    evidence: "Evidence",
    showOnChart: "Show on chart",
    hideOnChart: "Hide on chart",
    snooze: "Snooze 7 days",
    dismiss: "Dismiss",
    undo: "Undo",
    queuedNote: "Queued for the next deploy.",
    snoozedNote: "Snoozed until 2026-08-19.",
    dismissedNote: "Dismissed. It will return if the number worsens.",
    severity: {
      critical: "Losing money",
      warning: "Timing off",
      opportunity: "Upside",
    },
    items: {
      broken: {
        title: "/spring-promo has returned 404 since 08/07",
        evidence:
          "It still takes 214 clicks a day. At the 4.1% signup rate of comparable links that is about $310 of pipeline lost every day.",
        barsNote: "Daily clicks, last 7 days. Orange marks days after the break.",
        action: "Fix redirect",
      },
      mobile: {
        title: "/launch is 71% mobile but resolves to the desktop page",
        evidence:
          "Mobile share is 71.2% against a 44.0% account average — 1.6x. Mobile sessions leave 2.3x faster than desktop ones.",
        barsNote: "Mobile share of /launch versus the account average.",
        action: "Swap to mobile landing",
      },
      timing: {
        title: (peak: string) =>
          `The newsletter goes out at 07:00, three hours before a ${peak}x window`,
        evidence: (peak: string, slot: string) =>
          `Tuesday 10:00-12:00 runs ${peak}x an average hour. The 07:00 slot runs ${slot}x. Same list, three hours early.`,
        barsNote: "Clicks by two-hour bucket on Tuesday.",
        action: "Move send to Tue 10:00",
      },
    },
  },
  audience: {
    h2: "Who is clicking, and when",
    lede: "Device mix sets the page you should ship. The heatmap sets the hour you should send.",
    deviceTitle: "Devices",
    deviceHelp: "Share of clicks",
    techTitle: "Browser and OS",
    browserTab: "Browser",
    osTab: "OS",
    share: "Share",
    heatTitle: "Hour of week",
    heatHelp:
      "Pick a cell to read it. Each column is a two-hour bucket in your workspace timezone.",
    heatReading: "Reading",
    avgLabel: "Average hour",
    conclusion: (day: string, range: string, value: string, ratio: string) =>
      `${day} ${range} — ${value} clicks, ${ratio}x an average hour.`,
    peakPrefix: "Peak:",
    cellLabel: (day: string, range: string, value: string) =>
      `${day} ${range}, ${value} clicks`,
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    srDevice: "Device share of clicks",
    srTech: "Browser and OS share of clicks",
    name: "Name",
    terms: {
      mobile: "Mobile",
      desktop: "Desktop",
      tablet: "Tablet",
      chrome: "Chrome",
      safari: "Safari",
      edge: "Edge",
      firefox: "Firefox",
      otherBrowser: "Other",
      ios: "iOS",
      android: "Android",
      macos: "macOS",
      windows: "Windows",
      otherOs: "Other",
    },
  },
  flow: {
    h2: "Where the clicks come from",
    lede: "Left column is the source, right column is the link it fed. Ribbon width is volume.",
    sources: "Sources",
    links: "Links",
    attributed: (part: string, all: string, pct: string) =>
      `${part} of ${all} clicks carry a source (${pct}). The rest arrived without one.`,
    domainsTitle: "Referring domains",
    domainsHelp: "Attributed clicks and change against the previous period",
    domain: "Domain",
    clicks: "Clicks",
    change: "Change",
    srFlow: "Clicks from each source to each link",
    source: "Source",
    link: "Link",
    terms: {
      instagram: "Instagram",
      newsletter: "Newsletter",
      x: "X",
      direct: "Direct",
      search: "Search",
    },
  },
  table: {
    h2: "Link by link",
    lede: "Sort by any column. The last row keeps the arithmetic honest against the total above.",
    caption: "Top 8 links by clicks for the selected period",
    cols: {
      slug: "Link",
      clicks: "Clicks",
      unique: "Unique",
      mobile: "Mobile",
      status: "Status",
      delta: "Change",
    },
    sortHint: "Sort by",
    status: { live: "Live", broken: "404", paused: "Paused" },
    other: (n: string) => `Other ${n} links`,
    otherNote: "Everything outside the top 8",
    totalRow: "Total",
  },
  common: {
    up: "up",
    down: "down",
    flat: "flat",
    of: "of",
  },
};

export type Dict = typeof EN;

const KO: Dict = {
  brand: "Hopline",
  productLine: "링크 분석",
  workspace: "필드노트 스튜디오",
  skipToWork: "고칠 것으로 건너뛰기",
  header: {
    search: "링크·소스·태그 검색",
    searchKey: "K",
    notifications: "알림, 읽지 않음 3건",
    account: "조미라 계정 메뉴",
    accountInitials: "MC",
    language: "언어",
    langKo: "KO",
    langEn: "EN",
    langKoName: "한국어",
    langEnName: "영어",
    period: "조회 기간",
    updated: "갱신",
  },
  periods: { "7d": "7일", "28d": "28일", "90d": "90일" } as Record<
    PeriodId,
    string
  >,
  band: {
    h1: "오늘 뭘 고쳐야 하나",
    lede: "지금 클릭을 갉아먹는 것이 세 가지입니다. 아래 순서는 해야 할 일 순서입니다.",
    totalLabel: "총 클릭",
    vsPrev: "직전 기간 대비",
    uniqueLabel: "순 방문자",
    uniqueRead: "재방문 28.4% — 총 클릭은 사람 수가 아니라 도달로 읽으세요.",
    brokenLabel: "404로 사라진 클릭",
    brokenRead: "전부 링크 하나에서 나옵니다. 1번 항목을 보세요.",
    activeLabel: "활성 링크",
    activeRead: "이번 기간 신규, 전부 런치 페이지로 향합니다.",
    chartTitle: "기간별 클릭",
    chartHelp: "기간마다 읽히는 밀도를 유지하도록 묶었습니다.",
    markerPrefix: "차트에 표시함",
    clearMarker: "표시 지우기",
    srCaption: "선택한 기간의 구간별 클릭 수",
    srDate: "구간",
    srValue: "클릭",
    read: "판독",
  },
  todo: {
    h2: "이것부터 하세요",
    lede: "카드마다 근거 수치와 처방이 하나씩 붙어 있습니다. 배너가 아닙니다.",
    counter: (done: number, all: number) => `${all}건 중 ${done}건 처리`,
    evidence: "근거",
    showOnChart: "차트에 표시",
    hideOnChart: "표시 해제",
    snooze: "7일 미루기",
    dismiss: "무시",
    undo: "되돌리기",
    queuedNote: "다음 배포에 예약했습니다.",
    snoozedNote: "2026-08-19까지 미룸.",
    dismissedNote: "무시함. 수치가 나빠지면 다시 올라옵니다.",
    severity: {
      critical: "손실 발생",
      warning: "타이밍 어긋남",
      opportunity: "여지 있음",
    },
    items: {
      broken: {
        title: "/spring-promo가 08/07부터 404를 반환합니다",
        evidence:
          "그런데도 하루 214클릭이 들어옵니다. 유사 링크의 가입률 4.1%를 적용하면 하루 약 $310이 사라집니다.",
        barsNote: "최근 7일 일별 클릭. 주황은 장애 이후 날짜입니다.",
        action: "리디렉션 고치기",
      },
      mobile: {
        title: "/launch는 모바일이 71%인데 데스크톱 페이지로 갑니다",
        evidence:
          "모바일 비중 71.2%, 계정 평균 44.0%의 1.6배입니다. 모바일 세션은 데스크톱보다 2.3배 빨리 이탈합니다.",
        barsNote: "/launch 모바일 비중과 계정 평균 비교.",
        action: "모바일 랜딩으로 교체",
      },
      timing: {
        title: (peak: string) =>
          `뉴스레터 발송이 07:00 — 평균 ${peak}배 구간보다 세 시간 이릅니다`,
        evidence: (peak: string, slot: string) =>
          `화요일 10:00-12:00은 평균 시간대의 ${peak}배, 07:00은 ${slot}배입니다. 같은 명단을 세 시간 일찍 보내고 있습니다.`,
        barsNote: "화요일 2시간 구간별 클릭.",
        action: "화 10:00으로 발송 이동",
      },
    },
  },
  audience: {
    h2: "누가, 언제 누르나",
    lede: "기기 구성은 어떤 페이지를 내보낼지를, 히트맵은 몇 시에 보낼지를 정해줍니다.",
    deviceTitle: "기기",
    deviceHelp: "클릭 비중",
    techTitle: "브라우저·OS",
    browserTab: "브라우저",
    osTab: "OS",
    share: "비중",
    heatTitle: "요일·시간대",
    heatHelp:
      "셀을 고르면 판독이 바뀝니다. 열 하나는 2시간 구간, 워크스페이스 시간대 기준입니다.",
    heatReading: "판독",
    avgLabel: "평균 시간대",
    conclusion: (day: string, range: string, value: string, ratio: string) =>
      `${day} ${range} — ${value}클릭, 평균 시간대의 ${ratio}배.`,
    peakPrefix: "피크:",
    cellLabel: (day: string, range: string, value: string) =>
      `${day} ${range}, ${value}클릭`,
    days: ["월", "화", "수", "목", "금", "토", "일"],
    srDevice: "기기별 클릭 비중",
    srTech: "브라우저·OS별 클릭 비중",
    name: "이름",
    terms: {
      mobile: "모바일",
      desktop: "데스크톱",
      tablet: "태블릿",
      chrome: "Chrome",
      safari: "Safari",
      edge: "Edge",
      firefox: "Firefox",
      otherBrowser: "기타",
      ios: "iOS",
      android: "Android",
      macos: "macOS",
      windows: "Windows",
      otherOs: "기타",
    },
  },
  flow: {
    h2: "클릭은 어디서 오나",
    lede: "왼쪽이 유입 소스, 오른쪽이 그 소스가 먹인 링크입니다. 띠 두께가 곧 물량입니다.",
    sources: "소스",
    links: "링크",
    attributed: (part: string, all: string, pct: string) =>
      `전체 ${all}클릭 중 ${part}이 소스를 달고 왔습니다 (${pct}). 나머지는 소스가 없습니다.`,
    domainsTitle: "추천 도메인",
    domainsHelp: "소스가 확인된 클릭과 직전 기간 대비 증감",
    domain: "도메인",
    clicks: "클릭",
    change: "증감",
    srFlow: "소스별·링크별 클릭 수",
    source: "소스",
    link: "링크",
    terms: {
      instagram: "인스타그램",
      newsletter: "뉴스레터",
      x: "X",
      direct: "직접 유입",
      search: "검색",
    },
  },
  table: {
    h2: "링크별 성과",
    lede: "어느 열로든 정렬됩니다. 마지막 행이 위의 총합과 계산을 맞춥니다.",
    caption: "선택한 기간의 클릭 상위 8개 링크",
    cols: {
      slug: "링크",
      clicks: "클릭",
      unique: "순 방문",
      mobile: "모바일",
      status: "상태",
      delta: "증감",
    },
    sortHint: "정렬 기준",
    status: { live: "정상", broken: "404", paused: "중지" },
    other: (n: string) => `나머지 ${n}개 링크`,
    otherNote: "상위 8개 밖 전부",
    totalRow: "합계",
  },
  common: {
    up: "증가",
    down: "감소",
    flat: "유지",
    of: "중",
  },
};

export const COPY: Record<Lang, Dict> = { en: EN, ko: KO };
